# Generated by Django 4.2.4 on 2023-08-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('no_street', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.residence'),
        ),
    ]
